export const columns = [
  { name: "PRODUCT", uid: "product", sortable: true },
  { name: "SKU", uid: "sku", sortable: true },
  { name: "CATEGORY", uid: "category", sortable: true },
  { name: "STOCK", uid: "stock", sortable: true },
  { name: "PRICE", uid: "price", sortable: true },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ADDED", uid: "added", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

export const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

export const users = [
  {
    id: 1,
    name: "Handmade Pouch",
    variants: 3,
    sku: "302012",
    category: "Bag & Pouch",
    stock: 10,
    price: 121.0,
    status: "Low Stock",
    added: "29 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 2,
    name: "Smartwatch E2",
    variants: 2,
    sku: "302011",
    category: "Watch",
    stock: 204,
    price: 590.0,
    status: "Published",
    added: "24 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 3,
    name: "MacBook Pro M2",
    variants: 4,
    sku: "302010",
    category: "Laptop",
    stock: 45,
    price: 1299.0,
    status: "Published",
    added: "23 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 4,
    name: "Gaming Mouse",
    variants: 2,
    sku: "302009",
    category: "Computer Accessories",
    stock: 156,
    price: 89.99,
    status: "Published",
    added: "22 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 5,
    name: "Mechanical Keyboard",
    variants: 3,
    sku: "302008",
    category: "Computer Accessories",
    stock: 89,
    price: 159.99,
    status: "Published",
    added: "21 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 6,
    name: "Wireless Earbuds",
    variants: 4,
    sku: "302007",
    category: "Audio",
    stock: 0,
    price: 199.99,
    status: "Out of Stock",
    added: "20 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 7,
    name: "4K Monitor",
    variants: 2,
    sku: "302006",
    category: "Computer Accessories",
    stock: 12,
    price: 399.99,
    status: "Low Stock",
    added: "19 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 8,
    name: "Smartphone Stand",
    variants: 1,
    sku: "302005",
    category: "Accessories",
    stock: 245,
    price: 29.99,
    status: "Published",
    added: "18 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 9,
    name: "USB-C Hub",
    variants: 2,
    sku: "302004",
    category: "Computer Accessories",
    stock: 178,
    price: 79.99,
    status: "Published",
    added: "17 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 10,
    name: "Laptop Sleeve",
    variants: 3,
    sku: "302003",
    category: "Bag & Pouch",
    stock: 67,
    price: 39.99,
    status: "Published",
    added: "16 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 11,
    name: "Wireless Charger",
    variants: 2,
    sku: "302002",
    category: "Electronics",
    stock: 8,
    price: 49.99,
    status: "Low Stock",
    added: "15 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 12,
    name: "Smart Light Bulb",
    variants: 3,
    sku: "302001",
    category: "Smart Home",
    stock: 423,
    price: 29.99,
    status: "Published",
    added: "14 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 13,
    name: "Bluetooth Speaker",
    variants: 4,
    sku: "302000",
    category: "Audio",
    stock: 89,
    price: 129.99,
    status: "Published",
    added: "13 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 14,
    name: "Camera Lens",
    variants: 5,
    sku: "301999",
    category: "Photography",
    stock: 15,
    price: 899.99,
    status: "Low Stock",
    added: "12 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 15,
    name: "Fitness Tracker",
    variants: 3,
    sku: "301998",
    category: "Wearables",
    stock: 234,
    price: 149.99,
    status: "Published",
    added: "11 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 16,
    name: "Tablet Stand",
    variants: 2,
    sku: "301997",
    category: "Accessories",
    stock: 167,
    price: 34.99,
    status: "Published",
    added: "10 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 17,
    name: "Power Bank",
    variants: 3,
    sku: "301996",
    category: "Electronics",
    stock: 0,
    price: 59.99,
    status: "Out of Stock",
    added: "09 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 18,
    name: "Desk Lamp",
    variants: 4,
    sku: "301995",
    category: "Home Office",
    stock: 145,
    price: 79.99,
    status: "Published",
    added: "08 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 19,
    name: "Wireless Mouse",
    variants: 2,
    sku: "301994",
    category: "Computer Accessories",
    stock: 189,
    price: 49.99,
    status: "Published",
    added: "07 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 20,
    name: "iPad Case",
    variants: 5,
    sku: "301993",
    category: "Accessories",
    stock: 78,
    price: 44.99,
    status: "Published",
    added: "06 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 21,
    name: "Smart Watch Band",
    variants: 6,
    sku: "301992",
    category: "Wearables",
    stock: 256,
    price: 29.99,
    status: "Published",
    added: "05 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 22,
    name: "Webcam Cover",
    variants: 1,
    sku: "301991",
    category: "Computer Accessories",
    stock: 567,
    price: 9.99,
    status: "Published",
    added: "04 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 23,
    name: "Phone Gimbal",
    variants: 2,
    sku: "301990",
    category: "Photography",
    stock: 11,
    price: 129.99,
    status: "Low Stock",
    added: "03 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 24,
    name: "AirPods Case",
    variants: 4,
    sku: "301989",
    category: "Accessories",
    stock: 189,
    price: 19.99,
    status: "Published",
    added: "02 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 25,
    name: "Drawing Tablet",
    variants: 3,
    sku: "301988",
    category: "Computer Accessories",
    stock: 45,
    price: 299.99,
    status: "Published",
    added: "01 Dec 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 26,
    name: "Cable Organizer",
    variants: 2,
    sku: "301987",
    category: "Accessories",
    stock: 345,
    price: 14.99,
    status: "Published",
    added: "30 Nov 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 27,
    name: "Smart Scale",
    variants: 2,
    sku: "301986",
    category: "Smart Home",
    stock: 89,
    price: 79.99,
    status: "Published",
    added: "29 Nov 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 28,
    name: "Laptop Cooling Pad",
    variants: 3,
    sku: "301985",
    category: "Computer Accessories",
    stock: 134,
    price: 39.99,
    status: "Published",
    added: "28 Nov 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 29,
    name: "Phone Tripod",
    variants: 2,
    sku: "301984",
    category: "Photography",
    stock: 0,
    price: 24.99,
    status: "Out of Stock",
    added: "27 Nov 2022",
    image: "/placeholder.jpg",
  },
  {
    id: 30,
    name: "Screen Protector",
    variants: 5,
    sku: "301983",
    category: "Accessories",
    stock: 456,
    price: 19.99,
    status: "Published",
    added: "26 Nov 2022",
    image: "/placeholder.jpg",
  },
];
